### ISSUE TITLE
Rasterio not working in latest notebook image

### ISSUE THREAD

**Issue by alando46** [pangeo-data/helm-chart#74]
`docker run pangeo/notebook:86665a6` followed by `docker exec -it <name of container> bin/bash`
and finally, `python` and `import rasterio`. 

```
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/rasterio/__init__.py", line 22, in <module>
    from rasterio._base import gdal_version
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory
>>> import cartopy
>>> 
```
Anyone know of a way to configure the dockerfile so if a package doesn't install properly the build stops?

**Comment by guillaumeeb** [comment]
Hm, this may be more complicate than a package that ddidn't install properly. It is possible that rasterio package is properly installed, but it doesn't find a required dependency (e.g. GDAL), that has not been installed on the system.

#71 should solve that, conda environments are more self coherent that pip installs.

**Comment by alando46** [comment]
@guillaumeeb hmm it looks like [conda is already](https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/Dockerfile#L50) handling the rasterio installation.

**Comment by guillaumeeb** [comment]
Oh sorry, my bad!

**Comment by alando46** [comment]
`pip freeze | grep rasterio` gives me `rasterio==1.0.13`. 

```
jovyan@f70c3ddad94c:~$ gdalinfo
gdalinfo: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
```
If part of the discussion around https://github.com/pangeo-data/pangeo/issues/535 is in regards to setting up default dockerfiles for different types of deployments, I'd be happy to contribute to setting up a default dockerfile/image for EO workflows.

Haha sadly I just realized this isn't the first time I've talked to @scottyhq about issues installing gdal ;)

**Comment by jhamman** [comment]
@alando46 - I updated the docker image again today, mind trying the most current version?
